In [1]:
# fmt: off
%matplotlib inline
%config InlineBackend.figure_format = "retina"
%load_ext autoreload
%load_ext lab_black
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
import pickle
from mls_scf_tools.mls_pint import ureg
plt.style.use("mls_scf")
def vdir(obj):
    return [x for x in dir(obj) if not x.startswith('__')]
# fmt: on

In [2]:
%autoreload 2
import dualpy as dp
import astropy.units as units

In [3]:
u = ureg
# u = units

In [4]:
t = np.arange(10) * u.s
delta_t = 1.0 * u.s
t = dp.seed(t, "t")
delta_t = dp.seed(delta_t, "delta_t")

In [5]:
j = t.jacobians["t"]
jj = j.to(u.min)
print("=================================")
if u is ureg:
    print(j)
    print(j.todensearray().squeeze().to_base_units()[0])
    print(jj)
    print(jj.todensearray().squeeze().to_base_units()[0])
else:
    print(j)
    print(j.todensearray().squeeze().decompose()[0])
    print(jj)
    print(jj.todensearray().squeeze().decompose()[0])

Jacobian of type <class 'dualpy.diagonal_jacobians.SeedJacobian'>
Dependent shape is (10,) <10>
Independent shape is (10,) <10>
Combined they are (10, 10) <100>
Dummies are (1,) and (1,)
Units are d<second>/d<second> = <dimensionless>
data is (10,)
[1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0] dimensionless
Jacobian of type <class 'dualpy.diagonal_jacobians.SeedJacobian'>
Dependent shape is (10,) <10>
Independent shape is (10,) <10>
Combined they are (10, 10) <100>
Dummies are (1,) and (1,)
Units are d<minute>/d<second> = <minute / second>
data is (10,)
[1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0] dimensionless


In [6]:
import warnings

# warnings.filterwarnings("error", category=UserWarning)

In [7]:
z = t.to(u.min) + delta_t

In [8]:
print(z.jacobians["delta_t"])

Jacobian of type <class 'dualpy.dense_jacobians.DenseJacobian'>
Dependent shape is (10,) <10>
Independent shape is () <1>
Combined they are (10,) <10>
Dummies are (1,) and ()
Units are d<minute>/d<second> = <minute / second>
data is (10,)
data2d is (10, 1)


In [9]:
print(z.jacobians["delta_t"].todensearray())

[0.016666666666666666 0.016666666666666666 0.016666666666666666 0.016666666666666666 0.016666666666666666 0.016666666666666666 0.016666666666666666 0.016666666666666666 0.016666666666666666 0.016666666666666666] minute / second
